// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: settings.proto

package com.ananananzhuo.datastoredemo;

public interface SettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Settings)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 example_counter = 1;</code>
   * @return The exampleCounter.
   */
  int getExampleCounter();
}
